### ISSUE TITLE
Why you simply copied my repository and then changed all the copyright notices?

### ISSUE THREAD

**Issue by steve600** [siranen/HardWPF#1]
Hi,

I just want to know if there is a special reason why you've simply **copied** my repository, then **removed** all the copyright notices and **renamed** the project? Apparently you gave a lot of effort to replace my name with yours. Even the Readme file was taken 1 to 1 (simply translated into english)!

I think you haven't changed one line of code (except the copyright notices). You've just copied and renamed the Project!

**Is this a common practice in open source development?**

I'm a newcomer in terms of Github but there is a feature called Fork (the button can be found on the top right in the Corner). Ever heard of it? If not here you can find the Help-Article: https://help.github.com/articles/fork-a-repo/

How should we proceed now?

**Comment by siranen** [comment]
close this repo
